name: ticket_management
description: "Ticket management web application"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  easy_localization:
  mobile_scanner: ^4.0.1
  firebase_core: ^3.4.0
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  cloud_firestore: ^5.4.4
  firebase_auth: ^5.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  riverpod_generator: ^2.4.3
  build_runner: ^2.4.13
  custom_lint: ^0.6.7
  riverpod_lint: ^2.3.13

flutter:
  uses-material-design: true
  assets:
    - assets/locales/
